version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: class_schedule
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/class_schedule

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"

volumes:
  pg_data:
